// Generated by GitHub Copilot

/*---------------------------------------------------------------------------*/
// Include Files
/*---------------------------------------------------------------------------*/
// Compiler headers.
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>

// This file's header.
#include "struct_table_tests.h"

// Other headers.
#include "crc.h"
#include "tlv_struct.h"


/*---------------------------------------------------------------------------*/
// Typedefs
/*---------------------------------------------------------------------------*/
typedef struct
{
    uint8_t  byte;
    uint16_t word;
    uint32_t dword;
    char     string[6];
} message_t;

typedef struct
{
    uint8_t  guard_a;
    uint8_t  byte;
    uint8_t  guard_b;
    uint8_t  guard_c;
    uint16_t word;
    uint8_t  guard_d;
    uint8_t  guard_e;
    uint32_t dword;
    uint8_t  guard_f;
    uint8_t  guard_g;
    char     string[6];
    uint8_t  guard_h;
} guarded_message_t;


/*---------------------------------------------------------------------------*/
// Variables
/*---------------------------------------------------------------------------*/
static unsigned int g_test_pass = 0;
static unsigned int g_test_fail = 0;


/*---------------------------------------------------------------------------*/
// Prototypes
/*---------------------------------------------------------------------------*/ 
static void print_separator (void);
static void hex_dump (const char *text, const void *ptr, size_t size);
static void set_tlv_crc (uint8_t *buffer, size_t size);
static void expect_true (const char *name, bool condition);
static void expect_values (const char *name,
                           const message_t *value,
                           uint8_t exp_byte, uint16_t exp_word, uint32_t exp_dword,
                           const char *exp_string);
static void init_guarded_message (guarded_message_t *msg);
static bool guarded_message_intact (const guarded_message_t *msg);

static void run_struct_write_tests (void);
static void run_struct_parse_tests (void);


/*---------------------------------------------------------------------------*/
// Functions
/*---------------------------------------------------------------------------*/


void run_struct_table_tests (void)
{
    g_test_pass = 0;
    g_test_fail = 0;

    run_struct_write_tests ();
    run_struct_parse_tests ();

    print_separator ();
    printf ("Struct test summary: %u passed, %u failed\n", g_test_pass, g_test_fail);
}

static void run_struct_write_tests (void)
{
    message_t message = { 0x11, 0x2222, 0x33333333U, "ABCDE" };

    const tlv_offset_entry_t struct_table[] =
    {
        TLVSTRUCTENTRY(1, message_t, byte),
        TLVSTRUCTENTRY(2, message_t, word),
        TLVSTRUCTENTRY(3, message_t, dword),
        TLVSTRUCTENTRY(4, message_t, string),
        TLVSTRUCTENTRYEND
    };

    uint8_t buffer_small[8] = { 0 };
    uint8_t buffer_large[32] = { 0 };
    size_t bytes_written = 0;

    print_separator ();
    printf ("Struct write tests\n");

    bytes_written = tlv_write_struct (buffer_small, sizeof(buffer_small), struct_table, &message);
    expect_true ("struct write small buffer fails", bytes_written == 0);

    bytes_written = tlv_write_struct (buffer_large, sizeof(buffer_large), struct_table, &message);
    expect_true ("struct write large buffer succeeds", bytes_written == 25);

    if (bytes_written != 0)
    {
        hex_dump ("struct write buffer", buffer_large, bytes_written);

        expect_true ("struct write exact-fit succeeds",
                     tlv_write_struct (buffer_large, (unsigned int)bytes_written, struct_table, &message) == bytes_written);

        expect_true ("struct write exact-fit-1 fails",
                     tlv_write_struct (buffer_large, (unsigned int)(bytes_written - 1), struct_table, &message) == 0);
    }
}

static void run_struct_parse_tests (void)
{
    message_t message = { 0 };

    const tlv_offset_entry_t struct_table[] =
    {
        TLVSTRUCTENTRY(1, message_t, byte),
        TLVSTRUCTENTRY(2, message_t, word),
        TLVSTRUCTENTRY(3, message_t, dword),
        TLVSTRUCTENTRY(4, message_t, string),
        TLVSTRUCTENTRYEND
    };

    const tlv_offset_entry_t struct_table_reordered[] =
    {
        TLVSTRUCTENTRY(4, message_t, string),
        TLVSTRUCTENTRY(2, message_t, word),
        TLVSTRUCTENTRY(1, message_t, byte),
        TLVSTRUCTENTRY(3, message_t, dword),
        TLVSTRUCTENTRYEND
    };

    guarded_message_t guarded = { 0 };

    const tlv_offset_entry_t guarded_table[] =
    {
        { 1, 1, offsetof(guarded_message_t, byte) },
        { 2, 2, offsetof(guarded_message_t, word) },
        { 3, 4, offsetof(guarded_message_t, dword) },
        { 4, 6, offsetof(guarded_message_t, string) },
        TLVSTRUCTENTRYEND
    };

    size_t bytes_parsed = 0;

    uint8_t buffer_bad_crc[] =
    {
        0x01, 0x01, 0x11,
        0x02, 0x02, 0x22, 0x22,
        0x03, 0x04, 0x33, 0x33, 0x33, 0x33,
        0x04, 0x06, 'A', 'B', 'C', 'D', 'E', '\0',
        0x00, 0x00,
        0xFF, 0xFF
    };

    uint8_t buffer_bad_truncated[] =
    {
        0x01, 0x01, 0x11,
        0x02, 0x02, 0x22, 0x22,
        0x03, 0x04, 0x33, 0x33, 0x33, 0x33,
        0x04, 0x06, 'A', 'B', 'C', 'D', 'E', '\0'
    };

    uint8_t buffer_unknown_types[] =
    {
        0x01, 0x01, 0x11,
        0x55, 0x02, 0x55, 0x55,
        0x02, 0x02, 0x22, 0x22,
        0x66, 0x06, 0x66, 0x66, 0x66, 0x66, 0x66, 0x66,
        0x03, 0x04, 0x33, 0x33, 0x33, 0x33,
        0x77, 0x07, 0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 0x77,
        0x04, 0x06, 'A', 'B', 'C', 'D', 'E', '\0',
        0x33, 0x03, 0x33, 0x33, 0x33,
        0x00, 0x00,
        0x6C, 0x7E
    };

    uint8_t buffer_bad_lengths[] =
    {
        0x01, 0x01, 0x11,
        0x02, 0x02, 0x22, 0x22,
        0x03, 0x04, 0x33, 0x33, 0x33, 0x33,
        0x04, 0x20, 'A', 'B', 'C', 'D', 'E', '\0'
    };

    uint8_t buffer_bad_known_length[] =
    {
        0x01, 0x01, 0x11,
        0x02, 0x01, 0x22,
        0x03, 0x04, 0x33, 0x33, 0x33, 0x33,
        0x04, 0x06, 'A', 'B', 'C', 'D', 'E', '\0',
        0x00, 0x00,
        0x00, 0x00
    };

    uint8_t buffer_duplicate_type[] =
    {
        0x01, 0x01, 0x11,
        0x02, 0x02, 0x22, 0x22,
        0x02, 0x02, 0x99, 0x99,
        0x03, 0x04, 0x33, 0x33, 0x33, 0x33,
        0x04, 0x06, 'A', 'B', 'C', 'D', 'E', '\0',
        0x00, 0x00,
        0x00, 0x00
    };

    uint8_t buffer_missing_type[] =
    {
        0x01, 0x01, 0x11,
        0x02, 0x02, 0x22, 0x22,
        0x03, 0x04, 0x33, 0x33, 0x33, 0x33,
        0x00, 0x00,
        0x00, 0x00
    };

    uint8_t buffer_reordered_table[] =
    {
        0x01, 0x01, 0x11,
        0x02, 0x02, 0x22, 0x22,
        0x03, 0x04, 0x33, 0x33, 0x33, 0x33,
        0x04, 0x06, 'A', 'B', 'C', 'D', 'E', '\0',
        0x00, 0x00,
        0x00, 0x00
    };

    set_tlv_crc (buffer_bad_known_length, sizeof(buffer_bad_known_length));
    set_tlv_crc (buffer_duplicate_type, sizeof(buffer_duplicate_type));
    set_tlv_crc (buffer_missing_type, sizeof(buffer_missing_type));
    set_tlv_crc (buffer_reordered_table, sizeof(buffer_reordered_table));

    print_separator ();
    printf ("Struct parse tests\n");

    init_guarded_message (&guarded);
    bytes_parsed = tlv_parse_struct (buffer_bad_crc, sizeof(buffer_bad_crc), guarded_table, &guarded);
    expect_true ("struct parse bad CRC fails", bytes_parsed == 0);
    expect_true ("struct parse bad CRC keeps guards", guarded_message_intact (&guarded));

    init_guarded_message (&guarded);
    bytes_parsed = tlv_parse_struct (buffer_bad_truncated, sizeof(buffer_bad_truncated), guarded_table, &guarded);
    expect_true ("struct parse truncated fails", bytes_parsed == 0);
    expect_true ("struct parse truncated keeps guards", guarded_message_intact (&guarded));

    memset (&message, 0, sizeof(message));
    bytes_parsed = tlv_parse_struct (buffer_unknown_types, sizeof(buffer_unknown_types), struct_table, &message);
    expect_true ("struct parse unknown types succeeds", bytes_parsed == sizeof(buffer_unknown_types));
    expect_values ("struct parse unknown types values", &message,
                   0x11, 0x2222, 0x33333333U, "ABCDE");

    init_guarded_message (&guarded);
    bytes_parsed = tlv_parse_struct (buffer_bad_lengths, sizeof(buffer_bad_lengths), guarded_table, &guarded);
    expect_true ("struct parse overrun length fails", bytes_parsed == 0);
    expect_true ("struct parse overrun length keeps guards", guarded_message_intact (&guarded));

    init_guarded_message (&guarded);
    bytes_parsed = tlv_parse_struct (buffer_bad_known_length, sizeof(buffer_bad_known_length), guarded_table, &guarded);
    expect_true ("struct parse known type wrong length fails", bytes_parsed == 0);
    expect_true ("struct parse known type wrong length keeps guards", guarded_message_intact (&guarded));

    memset (&message, 0, sizeof(message));
    bytes_parsed = tlv_parse_struct (buffer_duplicate_type, sizeof(buffer_duplicate_type), struct_table, &message);
    expect_true ("struct parse duplicate type succeeds", bytes_parsed == sizeof(buffer_duplicate_type));
    expect_values ("struct parse duplicate type values", &message,
                   0x11, 0x9999, 0x33333333U, "ABCDE");

    memset (&message, 0, sizeof(message));
    memcpy (message.string, "ZZZZZ", sizeof(message.string));
    bytes_parsed = tlv_parse_struct (buffer_missing_type, sizeof(buffer_missing_type), struct_table, &message);
    expect_true ("struct parse missing type succeeds", bytes_parsed == sizeof(buffer_missing_type));
    expect_values ("struct parse missing type values", &message,
                   0x11, 0x2222, 0x33333333U, "ZZZZZ");

    memset (&message, 0, sizeof(message));
    bytes_parsed = tlv_parse_struct (buffer_reordered_table, sizeof(buffer_reordered_table), struct_table_reordered, &message);
    expect_true ("struct parse reordered table succeeds", bytes_parsed == sizeof(buffer_reordered_table));
    expect_values ("struct parse reordered table values", &message,
                   0x11, 0x2222, 0x33333333U, "ABCDE");
}

static void print_separator (void)
{
    printf ("--------------------------------------------------\n");
}

static void hex_dump (const char *text, const void *ptr, size_t size)
{
    const uint8_t *bytes = (const uint8_t *)ptr;
    size_t idx = 0;

    printf ("%s: ", text);
    for (idx = 0; idx < size; idx++)
    {
        printf ("%02x ", bytes[idx]);
    }
    printf ("\n");
}

static void set_tlv_crc (uint8_t *buffer, size_t size)
{
    if ((NULL != buffer) && (size >= 4))
    {
        uint16_t crc = crc_calculate (buffer, size - 2);

        buffer[size - 2] = (uint8_t)(crc & 0xFF);
        buffer[size - 1] = (uint8_t)((crc >> 8) & 0xFF);
    }
}

static void expect_true (const char *name, bool condition)
{
    if (condition)
    {
        g_test_pass++;
        printf ("PASS: %s\n", name);
    }
    else
    {
        g_test_fail++;
        printf ("FAIL: %s\n", name);
    }
}

static void expect_values (const char *name,
                           const message_t *value,
                           uint8_t exp_byte, uint16_t exp_word, uint32_t exp_dword,
                           const char *exp_string)
{
    bool ok = true;

    ok = ok && (NULL != value);
    if (ok)
    {
        ok = ok && (value->byte == exp_byte);
        ok = ok && (value->word == exp_word);
        ok = ok && (value->dword == exp_dword);
        ok = ok && (0 == memcmp (value->string, exp_string, sizeof(value->string)));
    }

    expect_true (name, ok);
}

static void init_guarded_message (guarded_message_t *msg)
{
    if (NULL != msg)
    {
        memset (msg, 0, sizeof(*msg));

        msg->guard_a = 0xA1;
        msg->guard_b = 0xB1;
        msg->guard_c = 0xA2;
        msg->guard_d = 0xB2;
        msg->guard_e = 0xA3;
        msg->guard_f = 0xB3;
        msg->guard_g = 0xA4;
        msg->guard_h = 0xB4;
    }
}

static bool guarded_message_intact (const guarded_message_t *msg)
{
    bool intact = false;

    if (NULL != msg)
    {
        intact = true;
        intact = intact && (msg->guard_a == 0xA1);
        intact = intact && (msg->guard_b == 0xB1);
        intact = intact && (msg->guard_c == 0xA2);
        intact = intact && (msg->guard_d == 0xB2);
        intact = intact && (msg->guard_e == 0xA3);
        intact = intact && (msg->guard_f == 0xB3);
        intact = intact && (msg->guard_g == 0xA4);
        intact = intact && (msg->guard_h == 0xB4);
    }

    return intact;
}

// End of struct_table_tests.c